# Generated by Django 5.2.6 on 2025-09-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='trap_id',
        ),
    ]
