# Generated by Django 5.2.6 on 2025-09-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
