# Generated by Django 5.2.6 on 2025-09-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_rename_device_id_device_trap_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="trap_id",
            new_name="device_id",
        ),
    ]
